INSERT INTO rol
VALUES (DEFAULT, 'ADMINISTRADOR'),
       (DEFAULT, 'JEFE_OBRA'),
       (DEFAULT, 'TRABAJADOR');
INSERT INTO tipo_jornal
VALUES (DEFAULT, 'COMUN'),
       (DEFAULT, 'LLUVIA'),
       (DEFAULT, 'EXTRA');
